[package]
name = "ecdsa-jwt"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22"
hex = "0.4"
jsonwebtoken = "9.3"
k256 = { version = "0.13", features = ["pem"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"